import blockContent from './blockContent'
import category from './category'
import post from './post'
import author from './author'
import patchNote from './patchNote'
import tierEntry from './tierEntry'
import game from './game'
import radarEvent from './radarEvent'
import gear from './gear'
import gearCategory from './gearCategory'
import gearBrand from './gearBrand'
import mediaBlock from './mediaBlock'
import guide from './guide'
import guideLEvel from './guideLEvel'
import guideType from './guideType'

export const schemaTypes = [post, author, category, blockContent, patchNote, tierEntry, game, radarEvent, gear, gearCategory, gearBrand, mediaBlock, guide, guideLEvel, guideType]
